### PR TITLE
Fixed #10 Replace request-json-light by superagent

### LINKED ISSUE #10: Replace 'request-json-light' by 'superagent'
It's not possible for now to integrate it in cozy-mobile.

### PR DESCRIPTION
**Pull request by kosssi**

### CODE REVIEW

**Comment by nono** [comment]
I think we should add tests before doing such a major change

**Comment by frankrousseau** [comment]
Any news about the current state of this PR?

**Comment by kosssi** [comment]
@frankrousseau the mobile app is not passed to superagent I make it this sprint so I add test for this PR next sprint.

**Comment by frankrousseau** [comment]
Ok

**Comment by frankrousseau** [comment]
@kosssi Any news? Should we close this PR?

**Pull request closed without merging**
